# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:                   kramdown
highlighter:                rouge
permalink:                  none
plugins:                    [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag, jekyll-multiple-languages-plugin]
future:                     false

# Language settings
languages:                  ["en", "it"]
exclude_from_localizations: ["javascript", "images", "css"]
default_locale_in_subfolder: false

sass:
  sass_dir: assets/css
  style: :nested

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Ahead of the Board Game"
description:	       "The fun of getting into board games"
author:              "4binary1"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
