# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'ABG'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
# - {icon: 'twitter', link: ''}
# - {icon: 'facebook', link: 'https://www.facebook.com/'}
- {icon: 'instagram', link: 'https://instagram.com/4binary1'}
# - {icon: 'envelope', link: 'mailto:'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

